# Generated by Django 6.0.5 on 2026-06-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organisationstyp', models.CharField(choices=[('schule', 'Schule'), ('hochschule', 'Hochschule'), ('unternehmen', 'Unternehmen'), ('verein', 'Verein'), ('bibliothek', 'Bibliothek'), ('sonstige', 'Sonstige')], max_length=50)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('is_seed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'organisation',
            },
        ),
    ]
