# Generated by Django 6.0.5 on 2026-06-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
                ('is_seed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'kategorie',
            },
        ),
        migrations.CreateModel(
            name='Gegenstandstyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('maximale_ausleihzeit', models.IntegerField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('is_seed', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gegenstandstypen', to='organisations.organisation')),
                ('kategorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gegenstandstypen', to='inventory.kategorie')),
            ],
            options={
                'db_table': 'gegenstandstyp',
            },
        ),
        migrations.CreateModel(
            name='Gegenstandsexemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventarnummer', models.CharField(max_length=255, unique=True)),
                ('zustand', models.CharField(choices=[('gut', 'Gut'), ('beschaedigt', 'Beschädigt'), ('defekt', 'Defekt'), ('verloren', 'Verloren')], default='gut', max_length=20)),
                ('verfuegbarkeitsstatus', models.CharField(choices=[('verfuegbar', 'Verfügbar'), ('reserviert', 'Reserviert'), ('ausgeliehen', 'Ausgeliehen'), ('nicht_verfuegbar', 'Nicht verfügbar')], default='verfuegbar', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('is_seed', models.BooleanField(default=False)),
                ('gegenstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplare', to='inventory.gegenstandstyp')),
            ],
            options={
                'db_table': 'gegenstandsexemplar',
            },
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
                ('is_seed', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standorte', to='organisations.organisation')),
            ],
            options={
                'db_table': 'standort',
            },
        ),
        migrations.AddField(
            model_name='gegenstandstyp',
            name='standort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gegenstandstypen', to='inventory.standort'),
        ),
    ]
