# Generated by Django 6.0.5 on 2026-06-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vollstaendiger_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwort_hash', models.CharField(max_length=255)),
                ('telefonnummer', models.CharField(blank=True, max_length=50, null=True)),
                ('benutzerrolle', models.CharField(choices=[('admin', 'Admin'), ('verleiher', 'Verleiher'), ('ausleiher', 'Ausleiher')], default='ausleiher', max_length=20)),
                ('kontostatus', models.CharField(choices=[('verifizierung_ausstehend', 'Verifizierung ausstehend'), ('aktiv', 'Aktiv'), ('gesperrt', 'Gesperrt'), ('geloescht', 'Gelöscht')], default='verifizierung_ausstehend', max_length=30)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('is_seed', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutzer', to='organisations.organisation')),
            ],
            options={
                'db_table': 'nutzer',
            },
        ),
    ]
