# Generated by Django 6.0.5 on 2026-05-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('requested', 'Angefragt'), ('borrowed', 'Ausgeliehen')], default='available', max_length=20)),
            ],
        ),
    ]
